// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClduu8BCXvslzgqZHcUMfy-cYrl5rX2lo',
    appId: '1:1023358873388:web:0198353bb9dfccf4290689',
    messagingSenderId: '1023358873388',
    projectId: 'notesminticflutter',
    authDomain: 'notesminticflutter.firebaseapp.com',
    storageBucket: 'notesminticflutter.appspot.com',
    measurementId: 'G-C53WKFQ831',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6B1H1RQwgVrVJK-0AUidKaIXeptG94Aw',
    appId: '1:1023358873388:android:7b47dd0f770c450d290689',
    messagingSenderId: '1023358873388',
    projectId: 'notesminticflutter',
    storageBucket: 'notesminticflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCN7J5B9cQBidNzMFAU9biF8TYvTF-JTw',
    appId: '1:1023358873388:ios:4c38c6e791614f8e290689',
    messagingSenderId: '1023358873388',
    projectId: 'notesminticflutter',
    storageBucket: 'notesminticflutter.appspot.com',
    iosClientId: '1023358873388-b5lsnrqmo4h3gk0kn7ido4a40cn9irgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteminticflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCN7J5B9cQBidNzMFAU9biF8TYvTF-JTw',
    appId: '1:1023358873388:ios:4c38c6e791614f8e290689',
    messagingSenderId: '1023358873388',
    projectId: 'notesminticflutter',
    storageBucket: 'notesminticflutter.appspot.com',
    iosClientId: '1023358873388-b5lsnrqmo4h3gk0kn7ido4a40cn9irgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteminticflutter',
  );
}
